package hibernate;
// Generated 2015-12-7 18:32:22 by Hibernate Tools 3.4.0.CR1

/**
 * AdminInfo generated by hbm2java
 */
public class AdminInfo implements java.io.Serializable {

	private String adminId;
	private String adminSex;
	private int adminAge;
	private String adminTel;
	private Integer adminFloorNum;

	public AdminInfo() {
	}

	public AdminInfo(String adminId, String adminSex, int adminAge) {
		this.adminId = adminId;
		this.adminSex = adminSex;
		this.adminAge = adminAge;
	}

	public AdminInfo(String adminId, String adminSex, int adminAge, String adminTel, Integer adminFloorNum) {
		this.adminId = adminId;
		this.adminSex = adminSex;
		this.adminAge = adminAge;
		this.adminTel = adminTel;
		this.adminFloorNum = adminFloorNum;
	}

	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	public String getAdminSex() {
		return this.adminSex;
	}

	public void setAdminSex(String adminSex) {
		this.adminSex = adminSex;
	}

	public int getAdminAge() {
		return this.adminAge;
	}

	public void setAdminAge(int adminAge) {
		this.adminAge = adminAge;
	}

	public String getAdminTel() {
		return this.adminTel;
	}

	public void setAdminTel(String adminTel) {
		this.adminTel = adminTel;
	}

	public Integer getAdminFloorNum() {
		return this.adminFloorNum;
	}

	public void setAdminFloorNum(Integer adminFloorNum) {
		this.adminFloorNum = adminFloorNum;
	}

}
