package hibernate;
// Generated 2015-11-27 20:15:26 by Hibernate Tools 4.0.0

/**
 * AdminInfo generated by hbm2java
 */
public class AdminInfo implements java.io.Serializable {

	private Integer id;
	private String name;
	private String sex;
	private Integer age;
	private String adminId;
	private String pwd;
	private String tel;

	public AdminInfo() {
	}

	public AdminInfo(String name, String adminId, String pwd) {
		this.name = name;
		this.adminId = adminId;
		this.pwd = pwd;
	}

	public AdminInfo(String name, String sex, Integer age, String adminId, String pwd, String tel) {
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.adminId = adminId;
		this.pwd = pwd;
		this.tel = tel;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

}
