package hibernate;
// Generated 2015-12-7 18:32:22 by Hibernate Tools 3.4.0.CR1

/**
 * DormScoreId generated by hbm2java
 */
public class DormScoreId implements java.io.Serializable {

	private String dormFloorNum;
	private String dormDormNum;

	public DormScoreId() {
	}

	public DormScoreId(String dormFloorNum, String dormDormNum) {
		this.dormFloorNum = dormFloorNum;
		this.dormDormNum = dormDormNum;
	}

	public String getDormFloorNum() {
		return this.dormFloorNum;
	}

	public void setDormFloorNum(String dormFloorNum) {
		this.dormFloorNum = dormFloorNum;
	}

	public String getDormDormNum() {
		return this.dormDormNum;
	}

	public void setDormDormNum(String dormDormNum) {
		this.dormDormNum = dormDormNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DormScoreId))
			return false;
		DormScoreId castOther = (DormScoreId) other;

		return ((this.getDormFloorNum() == castOther.getDormFloorNum()) || (this.getDormFloorNum() != null
				&& castOther.getDormFloorNum() != null && this.getDormFloorNum().equals(castOther.getDormFloorNum())))
				&& ((this.getDormDormNum() == castOther.getDormDormNum())
						|| (this.getDormDormNum() != null && castOther.getDormDormNum() != null
								&& this.getDormDormNum().equals(castOther.getDormDormNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDormFloorNum() == null ? 0 : this.getDormFloorNum().hashCode());
		result = 37 * result + (getDormDormNum() == null ? 0 : this.getDormDormNum().hashCode());
		return result;
	}

}
