package hibernate;
// Generated 2015-12-7 18:32:22 by Hibernate Tools 3.4.0.CR1

/**
 * DormScore generated by hbm2java
 */
public class DormScore implements java.io.Serializable {

	private DormScoreId id;
	private int dormScore;
	private String dormScoreCondition;
	private String dormScoreTime;

	public DormScore() {
	}

	public DormScore(DormScoreId id, int dormScore, String dormScoreCondition, String dormScoreTime) {
		this.id = id;
		this.dormScore = dormScore;
		this.dormScoreCondition = dormScoreCondition;
		this.dormScoreTime = dormScoreTime;
	}

	public DormScoreId getId() {
		return this.id;
	}

	public void setId(DormScoreId id) {
		this.id = id;
	}

	public int getDormScore() {
		return this.dormScore;
	}

	public void setDormScore(int dormScore) {
		this.dormScore = dormScore;
	}

	public String getDormScoreCondition() {
		return this.dormScoreCondition;
	}

	public void setDormScoreCondition(String dormScoreCondition) {
		this.dormScoreCondition = dormScoreCondition;
	}

	public String getDormScoreTime() {
		return this.dormScoreTime;
	}

	public void setDormScoreTime(String dormScoreTime) {
		this.dormScoreTime = dormScoreTime;
	}

}
