package hibernate;
// Generated 2015-11-27 20:15:26 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice implements java.io.Serializable {

	private Integer id;
	private String title;
	private String content;
	private Date startDate;
	private Date endDate;
	private String falg;

	public Notice() {
	}

	public Notice(String title, String content, Date startDate, Date endDate) {
		this.title = title;
		this.content = content;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Notice(String title, String content, Date startDate, Date endDate, String falg) {
		this.title = title;
		this.content = content;
		this.startDate = startDate;
		this.endDate = endDate;
		this.falg = falg;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getFalg() {
		return this.falg;
	}

	public void setFalg(String falg) {
		this.falg = falg;
	}

}
