package hibernate;
// Generated 2015-12-7 18:32:22 by Hibernate Tools 3.4.0.CR1

/**
 * StuScore generated by hbm2java
 */
public class StuScore implements java.io.Serializable {

	private String stuNum;
	private int score;
	private String conditiion;
	private String date;

	public StuScore() {
	}

	public StuScore(String stuNum, int score, String conditiion, String date) {
		this.stuNum = stuNum;
		this.score = score;
		this.conditiion = conditiion;
		this.date = date;
	}

	public String getStuNum() {
		return this.stuNum;
	}

	public void setStuNum(String stuNum) {
		this.stuNum = stuNum;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public String getConditiion() {
		return this.conditiion;
	}

	public void setConditiion(String conditiion) {
		this.conditiion = conditiion;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
