package hibernate;
// Generated 2015-11-27 20:15:26 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * StuScore generated by hbm2java
 */
public class StuScore implements java.io.Serializable {

	private String stuNum;
	private String name;
	private int score;
	private String cose;
	private Date date;

	public StuScore() {
	}

	public StuScore(String stuNum, String name, int score, String cose, Date date) {
		this.stuNum = stuNum;
		this.name = name;
		this.score = score;
		this.cose = cose;
		this.date = date;
	}

	public String getStuNum() {
		return this.stuNum;
	}

	public void setStuNum(String stuNum) {
		this.stuNum = stuNum;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public String getCose() {
		return this.cose;
	}

	public void setCose(String cose) {
		this.cose = cose;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
